joint_state_controller:
    type: joint_state_controller/JointStateController

    publish_rate: 50

jaco_traj_controller:
    type: effort_controllers/JointTrajectoryController

    joints:
        - jaco_joint_1
        - jaco_joint_2
        - jaco_joint_3
        - jaco_joint_4
        - jaco_joint_5
        - jaco_joint_6
          
    gains:
        jaco_joint_1: {p: 500.0, d: 50.0}
        jaco_joint_2: {p: 500.0, d: 50.0}
        jaco_joint_3: {p: 500.0, d: 50.0}
        jaco_joint_4: {p: 500.0, d: 50.0}
        jaco_joint_5: {p: 500.0, d: 50.0}
        jaco_joint_6: {p: 500.0, d: 50.0}
